version: '3'

services:
  server:    
    build: .
    volumes:
      - ./:/app
    ports:
      - "3000:3000"    
    env_file:
      - .env  
    links:
      - database       
    command: ['node', './build/index.js']
  database:
    image: mariadb        
    volumes:
      - database-data:/var/lib/mariadb/data
    ports:
      - "3306:3306"  
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cflow
      - MYSQL_USER=cflow
      - MYSQL_PASSWORD=formparser      
volumes:
  database-data: {}    